/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/flaresolverr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** FlareSolverr server used for sources behind Cloudflare */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.flareSolverrSettings"];
                    };
                };
            };
        };
        /** Set the FlareSolverr server (empty URL disables it), checked before saving. Sources behind Cloudflare are queried while it is set. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description FlareSolverr URL */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.flareSolverrSettings"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.apiError"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/instance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change the instance language (catalog, UI and sources) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Language */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.instanceUpdate"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.apiError"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accounts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["store.User"][];
                    };
                };
            };
        };
        put?: never;
        /** Create an account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Account */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.newUser"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["store.User"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.apiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an account */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.apiError"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Credentials */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.credentials"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["store.User"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.apiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Titles of a genre, most popular first */
        get: {
            parameters: {
                query: {
                    /** @description movie or tv */
                    type: string;
                    /** @description TMDB genre ID */
                    genre: number;
                    /** @description Page, from 1 */
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["tmdb.Item"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Genres of movies or shows */
        get: {
            parameters: {
                query: {
                    /** @description movie or tv */
                    type: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["tmdb.Genre"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home rows (all, movies or shows) */
        get: {
            parameters: {
                query?: {
                    /** @description movie or tv, empty for both */
                    type?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.row"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search movies and shows */
        get: {
            parameters: {
                query: {
                    /** @description Query */
                    q: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["tmdb.Item"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public instance information: setup state and language */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.instanceInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** "My list" of the profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["store.ListItem"][];
                    };
                };
            };
        };
        /** Add a title to "My list" */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Title */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["store.ListItem"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/list/{type}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a title from "My list" */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description movie or tv */
                    type: string;
                    /** @description TMDB ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** "Continue watching" row of the profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["store.Progress"][];
                    };
                };
            };
        };
        /** Save the playback position */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Position */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["store.Progress"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/progress/{type}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Watch progress of a title (every episode for a show), most recent first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description movie or tv */
                    type: string;
                    /** @description TMDB ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["store.Progress"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current account */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["store.User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change the account password (logs out every session) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Passwords */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.passwordChange"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.apiError"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve a link into a proxied stream URL */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Link token */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.playRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.playResponse"];
                    };
                };
                /** @description Bad Gateway */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.apiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profiles of the account */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["store.Profile"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a profile (5 max per account) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Profile */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.profileBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["store.Profile"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.apiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a profile and its history */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Profile ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Rename or change the avatar of a profile */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Profile ID */
                    id: number;
                };
                cookie?: never;
            };
            /** @description Profile */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.profileBody"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create the first admin account and pick the instance language (only while no account exists), then log in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Admin credentials and language */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.setupRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["store.User"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.apiError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/titles/tv/{id}/seasons/{season}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Episodes of a season */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description TMDB ID */
                    id: number;
                    /** @description Season number */
                    season: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["tmdb.Episode"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/titles/{type}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Details of a movie or show */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description movie or tv */
                    type: string;
                    /** @description TMDB ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["tmdb.Details"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/titles/{type}/{id}/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find links for a movie or an episode across the sources of the instance language */
        get: {
            parameters: {
                query?: {
                    /** @description Season (shows) */
                    season?: number;
                    /** @description Episode (shows) */
                    episode?: number;
                };
                header?: never;
                path: {
                    /** @description movie or tv */
                    type: string;
                    /** @description TMDB ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.link"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/titles/{type}/{id}/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opening and ending of a movie or episode, for the skip buttons (empty when unknown or turned off for the profile) */
        get: {
            parameters: {
                query: {
                    /** @description Season (shows) */
                    season?: number;
                    /** @description Episode (shows) */
                    episode?: number;
                    /** @description Length of the file being played, in seconds */
                    duration: number;
                };
                header?: never;
                path: {
                    /** @description movie or tv */
                    type: string;
                    /** @description TMDB ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["aniskip.Segment"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "aniskip.Segment": {
            end: number;
            /** @enum {string} */
            kind: "intro" | "credits";
            start: number;
        };
        "api.apiError": {
            /** @enum {string} */
            code: "invalid_json" | "unsupported_media_type" | "not_logged_in" | "session_expired" | "admin_only" | "missing_profile" | "unknown_profile" | "internal" | "not_found" | "invalid_credentials" | "already_set_up" | "username_required" | "password_length" | "unsupported_language" | "wrong_password" | "name_required" | "unknown_avatar" | "profile_limit" | "last_profile" | "username_taken" | "delete_self" | "invalid_id" | "invalid_request" | "episode_required" | "tmdb_unreachable" | "invalid_link" | "link_dead" | "invalid_progress" | "flaresolverr_unreachable";
            error: string;
        };
        "api.credentials": {
            password: string;
            username: string;
        };
        "api.flareSolverrSettings": {
            /** @description URL of the FlareSolverr server, "" when disabled. */
            url: string;
        };
        "api.instanceInfo": {
            /**
             * @description Language of the instance: catalog, UI and sources.
             * @enum {string}
             */
            language: "en" | "fr";
            /** @description Languages that can be picked at setup: the ones supported end to end. */
            languages: components["schemas"]["api.language"][];
            /** @description SetupNeeded is true until the first admin account exists. */
            setupNeeded: boolean;
        };
        "api.instanceUpdate": {
            /** @enum {string} */
            language: "en" | "fr";
        };
        "api.language": {
            /** @enum {string} */
            code: "en" | "fr";
            label: string;
        };
        "api.link": {
            dead: boolean;
            hoster: string;
            lang: string;
            quality: string;
            source: string;
            token: string;
        };
        "api.newUser": {
            isAdmin: boolean;
            password: string;
            username: string;
        };
        "api.passwordChange": {
            current: string;
            new: string;
        };
        "api.playRequest": {
            token: string;
        };
        "api.playResponse": {
            /** @enum {string} */
            kind: "hls" | "file";
            url: string;
        };
        "api.profileBody": {
            avatar: string;
            name: string;
            /** @description SkipSegments shows the "skip intro" and "skip credits" buttons. */
            skipSegments: boolean;
        };
        "api.row": {
            items: components["schemas"]["tmdb.Item"][];
            /** @description Ranked rows are Top 10s: the UI draws the rank next to each poster. */
            ranked: boolean;
            title: string;
        };
        "api.setupRequest": {
            /** @enum {string} */
            language: "en" | "fr";
            password: string;
            username: string;
        };
        "store.ListItem": {
            id: number;
            poster: string;
            title: string;
            type: string;
        };
        "store.Profile": {
            avatar: string;
            id: number;
            name: string;
            /** @description SkipSegments shows the "skip intro" and "skip credits" buttons. */
            skipSegments: boolean;
        };
        "store.Progress": {
            backdrop: string;
            duration: number;
            episode: number;
            id: number;
            position: number;
            poster: string;
            season: number;
            title: string;
            type: string;
        };
        "store.User": {
            id: number;
            isAdmin: boolean;
            username: string;
        };
        "tmdb.Details": {
            backdrop: string;
            /**
             * @description Badge is the Netflix-style tag shown on cards: in today's Top 10, newly released, or a show with a new
             *     episode or season (details only).
             * @enum {string}
             */
            badge: "top10" | "new" | "newEpisode" | "newSeason";
            cast: string[];
            genres: components["schemas"]["tmdb.Genre"][];
            id: number;
            /** @description Logo is the title artwork (transparent PNG), set on the home banner titles and on details. */
            logo: string;
            originalTitle: string;
            overview: string;
            poster: string;
            rating: number;
            runtime: number;
            seasons: components["schemas"]["tmdb.Season"][];
            similar: components["schemas"]["tmdb.Item"][];
            title: string;
            type: string;
            year: number;
        };
        "tmdb.Episode": {
            name: string;
            number: number;
            overview: string;
            runtime: number;
            still: string;
        };
        "tmdb.Genre": {
            id: number;
            name: string;
        };
        "tmdb.Item": {
            backdrop: string;
            /**
             * @description Badge is the Netflix-style tag shown on cards: in today's Top 10, newly released, or a show with a new
             *     episode or season (details only).
             * @enum {string}
             */
            badge: "top10" | "new" | "newEpisode" | "newSeason";
            id: number;
            /** @description Logo is the title artwork (transparent PNG), set on the home banner titles and on details. */
            logo: string;
            overview: string;
            poster: string;
            rating: number;
            title: string;
            type: string;
            year: number;
        };
        "tmdb.Season": {
            episodes: number;
            name: string;
            number: number;
            poster: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
