-- Unix timestamps (seconds) everywhere, compared with now() in queries.
CREATE TABLE users (
    id            BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT    NOT NULL,
    password_hash TEXT    NOT NULL,
    is_admin      BOOLEAN NOT NULL DEFAULT false,
    created_at    BIGINT  NOT NULL DEFAULT extract(epoch FROM now())::bigint
);
CREATE UNIQUE INDEX users_username ON users (lower(username));

CREATE TABLE sessions (
    token_hash TEXT   PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    expires_at BIGINT NOT NULL
);

CREATE TABLE profiles (
    id            BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name          TEXT    NOT NULL,
    avatar        TEXT    NOT NULL,
    -- "Skip intro" / "Skip credits" buttons, on by default.
    skip_segments BOOLEAN NOT NULL DEFAULT true,
    created_at    BIGINT  NOT NULL DEFAULT extract(epoch FROM now())::bigint
);

CREATE TABLE my_list (
    profile_id BIGINT  NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
    media_type TEXT    NOT NULL,
    tmdb_id    INTEGER NOT NULL,
    title      TEXT    NOT NULL,
    poster     TEXT    NOT NULL,
    added_at   BIGINT  NOT NULL DEFAULT extract(epoch FROM now())::bigint,
    PRIMARY KEY (profile_id, media_type, tmdb_id)
);

-- One row per movie, or per episode of a show (season/episode are 0 for movies).
CREATE TABLE progress (
    profile_id BIGINT           NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
    media_type TEXT             NOT NULL,
    tmdb_id    INTEGER          NOT NULL,
    season     INTEGER          NOT NULL DEFAULT 0,
    episode    INTEGER          NOT NULL DEFAULT 0,
    title      TEXT             NOT NULL,
    poster     TEXT             NOT NULL,
    backdrop   TEXT             NOT NULL,
    position   DOUBLE PRECISION NOT NULL,
    duration   DOUBLE PRECISION NOT NULL,
    updated_at BIGINT           NOT NULL DEFAULT extract(epoch FROM now())::bigint,
    PRIMARY KEY (profile_id, media_type, tmdb_id, season, episode)
);
CREATE INDEX progress_recent ON progress (profile_id, updated_at DESC);

-- Source URLs, synced from vStream's sites.json.
CREATE TABLE sources (
    id  TEXT PRIMARY KEY,
    url TEXT NOT NULL DEFAULT ''
);

CREATE TABLE settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
